version: "3.0"

services:
  elasticsearch:
    build:
      context: ./elasticsearch
    container_name: elasticsearch-service
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - elk
  logstash:
    build:
      context: ./logstash
    container_name: logstash-service
    ports:
      - "4560:4560"
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
#      - type: bind
#        source: ../logs
#        target: /usr/share/logstash/pipeline
#        read_only: true
#      - ./logstash/pipeline:/usr/share/logstash/pipeline
#      - ./logstash/config:/usr/share/logstash/config
    networks:
      - elk
    depends_on:
      - elasticsearch
  kibana:
    build:
      context: ./kibana
    container_name: kibana-service
    ports:
      - "5601:5601"
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    networks:
      - elk
    depends_on:
      - elasticsearch
networks:
  elk:
    driver: bridge