server:
  port: 8081
spring:
  cloud:
    function:
      definition: goodsChangeEvent
    stream:
      bindings:
        goodsChangeEvent-in-0:
          destination: goods-change-event
      rabbit:
        bindings:
          goodsChangeEvent-in-0:
            consumer:
              binding-routing-key: goods-change-event


  redis:
    host: localhost
    port: 6379
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest

