server:
  port: 8081
spring:
  cloud:
    function:
      definition: goodsCacheEvict
    stream:
      bindings:
        goodsCacheEvict-in-0:
          destination: goods-cache-topic
      rabbit:
        bindings:
          goodsCacheEvict-in-0:
            consumer:
              binding-routing-key: goods-cache-topic


  redis:
    host: localhost
    port: 6379
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest

