spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8081
          predicates:
            - Path=/hello-world/**
          filters:
            - RewritePath=/hello-world/(?<segment>.*), /$\{segment}

management:
  endpoint:
    gateway:
      enabled: true