###
GET http://127.0.0.1:8080/retrofit/hello

###
GET http://127.0.0.1:8080/retrofit/status/200

###
GET http://127.0.0.1:8080/retrofit/status/200/error

###
GET http://127.0.0.1:8080/retrofit/status/400

###
GET http://127.0.0.1:8080/retrofit/status/500
