spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_batch
    username: sa
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  batch:
    job:
      names: ${job.names:NONE}
