spring:
  profiles:
    active: local
  application:
    name: LOG_SERVICE_API
#logging:
#  file:
#    path: ./logs/${spring.profiles.active}
#    name: spring-log
#  logback:
#    rollingpolicy:
#      max-file-size: 10MB
#      total-size-cap: 1GB
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml