spring:
  profiles:
    active: local

#logging:
#  file:
#    path: ./logs/${spring.profiles.active}
#    name: spring-log
#  logback:
#    rollingpolicy:
#      max-file-size: 10MB
#      total-size-cap: 1GB
