spring:
  batch:
    job:
      name: ${job.names:NONE}
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
    url: jdbc:h2:mem:testdb

