spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: sa
    password: 1234
    url: jdbc:mariadb://127.0.0.1:3306/spring_batch
  batch:
    job:
      names: ${job.name:NONE}