spring:
  application:
    name: SpringWebsocket
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true



management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  tomcat:
    mbeanregistry:
      enabled: true



