version: "3"
services:
  mariadb:
#    platform: linux/x86_64
    image: mariadb:10.5.8
    container_name: "mariadb"
    # mac m1 칩 사용 시 에러
#    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
