services:
  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testdb
      TZ: Asia/Seoul