spring:
  jpa:
    generate-ddl: true
    show-sql: true
  batch:
    job:
      name: ${job.names:NONE}
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: ${datasource.member.driver-class-name}
    username: ${datasource.member.username}
    password: ${datasource.member.password}
    url: ${datasource.member.url}
    hikari:
      pool-name: ${datasource.member.hikari.pool-name}

datasource:
  member:
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
    url: jdbc:h2:mem:member
    hikari:
      pool-name: member-hikari-pool
  order:
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
    url: jdbc:h2:mem:order
    hikari:
      pool-name: order-hikari-pool

logging.level:
  org.springframework.transaction.interceptor: trace
