version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  # networks:
  #   backend:
  #     aliases:
  #       - kafka
  # zookeeper:
  #   image: 'wurstmeister/zookeeper'
  #   ports:
  #     - 2181:2181
  #   networks:
  #     backend:
  #       aliases:
  #         - zookeeper
  # kafka:
  #   image: wurstmeister/kafka
  #   ports:
  #     - 9092:9092
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: kafka
  #     KAFKA_ADVERTISED_PORT: 9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_CREATE_TOPICS: dress:1:1,ratings:1:1
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   depends_on:
  #     - zookeeper
  #   networks:
  #     backend:
  #       aliases:
  #         - kafka
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      backend:
        aliases:
          - redis
networks:
  backend: