version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus:/prometheus
    ports:
      - 9090:9090
    command: # web.enalbe-lifecycle은 api 재시작없이 설정파일들을 reload 할 수 있게 해줌
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    environment:
      TZ: 'Asia/Seoul'
  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
    environment:
      TZ: 'Asia/Seoul'
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      TZ: 'Asia/Seoul'
  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - 5000:5000/tcp
      - 5000:5000/udp
      - 9600:9600
    environment:
      TZ: 'Asia/Seoul'
      LS_JAVA_OPTS: '-Xmx256m -Xms256m'
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      TZ: 'Asia/Seoul'
      ES_JAVA_OPTS: '-Xms1g -Xmx1g'
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    environment:
      TZ: 'Asia/Seoul'
      LS_JAVA_OPTS: '-Xms1g -Xmx1g'
    depends_on:
      - elasticsearch
