spring:
  batch:
    job:
      names: ${job.names:NONE}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  datasource:

    hikari:
      #      connection-timeout: 1000
      #      maximum-pool-size: 2
      #      idle-timeout: 5
      connection-test-query: SELECT 1
    #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #    url: jdbc:log4jdbc:h2:mem:test
    dbcp2:
      validation-query: SELECT 1
