spring:
  batch:
    job:
      names: ${job.names:NONE}
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_batch
    driver-class-name: org.mariadb.jdbc.Driver
    username: sa
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
