version: "3"
services:
  mariadb:
    image: mariadb:10.5.8
    container_name: "mariadb_container"
    # mac m1 칩 사용 시 에러
    #    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: spring_batch
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
#  mongodb:
#    image: mongo
#    container_name: "mongodb_container"
#    #    entrypoint: [ "mongod", "--auth" ]
#    volumes:
#      - ./mongodb/data:/data/db
#    ports:
#      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: yhnoh
#      MONGO_INITDB_ROOT_PASSWORD: 1234
#  mongo-express:
#    image: mongo-express
#    container_name: "mongo-express_container"
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
#      ME_CONFIG_SERVER: mongodb
#    depends_on:
#      - mongodb